services:
    web:
        container_name: web
        build:
            context: ../web
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - postgresql
            - redis

    postgresql:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgresql:/var/lib/postgresql/data

    redis:
        image: redis:latest

volumes:
    postgresql:
