services:
    web:
        image: web
        container_name: web
        env_file:
            - .env
        build:
            context: ../web
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - postgresql
            - redis

    postgresql:
        image: postgres:latest
        env_file:
            - .env
        volumes:
            - postgresql:/var/lib/postgresql/data

    redis:
        image: redis:latest
        env_file:
            - .env

volumes:
    postgresql:
