services:
    web:
        image: web
        container_name: web
        build:
            context: ../web
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - postgresql
            - redis
        deploy:
            resources:
                limits:
                    memory: '2g'
                    cpus: '2'

    postgresql:
        image: postgres:latest
        environment:
            POSTGRES_USER: TODO
            POSTGRES_PASSWORD: TODO
            POSTGRES_DB: TODO
        volumes:
            - postgresql:/var/lib/postgresql/data

    redis:
        image: redis:latest

volumes:
    postgresql:
