name: Test Organization Secrets

on:
    workflow_dispatch: # Manuel çalıştırma için

jobs:
    test-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Code
              uses: actions/checkout@v4

            - name: Check Secret Access
              env:
                  TEST_SECRET: ${{ secrets.SERVER_SSH_KEY }} # Buraya test etmek istediğin secret'ın adını yaz
              run: |
                  if [ -z "$TEST_SECRET" ]; then
                    echo "❌ Secret is NOT accessible!"
                    exit 1
                  else
                    echo "✅ Secret is accessible! Value length: ${#TEST_SECRET}"
                  fi
